### ISSUE TITLE
candybar segmentation fault

### ISSUE THREAD

**Issue by orschiro** [Lokaltog/candybar#95]
Hi there,

I get a segfault when running candybar:

```
~ candybar 
[20:47:29] INFO candybar beta-git-421.51429f5 (Jun 12 2014 20:43:34)
[20:47:31] INFO using config file '/home/orschiro/.config/candybar/config.json'
[20:47:31] INFO loading theme 'file:////usr/share/candybar/theme-default/index.html'
[20:47:32] WARNING loading of '//usr/lib/candybar/libwidget_now_playing_mpd' (now_playing_mpd) failed
[1]    13416 segmentation fault (core dumped)  candybar
```

How can I debug it and provide you with more useful information?

Thanks ahead!
##

**Comment by Lokaltog** [comment]
Thanks for reporting the issue here!

First of all, could you try to disable the battery widget (remove it from config.json)? Candybar may sometimes segfault if it's enabled and fails, see #64 for details.

If disabling the battery widget doesn't work and it still segfaults even after removing it from config.json it would be very helpful if you could compile a debug build accoding to [these](https://github.com/Lokaltog/candybar/blob/develop/docs/CONTRIBUTING.asciidoc#debugdevelopment-build) instructions, then run the resulting build in gdb: `gdb candybar`; type `run` in gdb, and when it segfaults run the `where` command in gdb to get a backtrace. This should help pinpoint the issue, let me know if you need any more help with the debug build.

**Comment by orschiro** [comment]
This is strange. Do I have to create `config.json` manually?

```
~ cat /home/orschiro/.config/candybar/config.json
cat: /home/orschiro/.config/candybar/config.json: No such file or directory
```

**Comment by orschiro** [comment]
I created the file manually and launched it again. Now candybar does not segfault but remains white:

![](http://i.imgur.com/sBo2ZpJ.png)

**Comment by Lokaltog** [comment]
Ah, the theme URI hasn't been inserted. Try to copy config.json from /etc/xdg/candybar/config.json and modify that one instead.

**Comment by orschiro** [comment]
So, I removed the battery widget but it is still crashing. I will follow your instructions to debug it. Thanks!

```
{                                                                                  
    "height": 24,                                                                  
    "position": "top",                                                             
    "monitor": 0,                                                                  
    "theme": {                                                                     
        "uri": "file:////usr/share/candybar/theme-default/index.html",             
        "config": {}                                                               
    },                                                                             
    "widgets": [                                                                   
        {                                                                          
            "module": "desktops",                                                  
            "config": {}                                                           
        },                                                                         
        {                                                                          
            "module": "window_title",                                              
            "config": {}                                                           
        },                                                                         
        {                                                                          
            "module": "now_playing_mpd",                                           
            "config": {}                                                           
        },                                                                         
        {                                                                          
            "module": "volume",                                                    
            "config": {}                                                           
        },                                                                         
        {                                                                          
            "module": "weather",                                                   
            "config": {}                                                           
        },                                                                         
        {                                                                          
            "module": "external_ip",                                               
            "config": {}                                                           
        },                                                                         
        {                                                                          
            "module": "datetime",                                                  
            "config": {}                                                           
        }                                                                                                                                                                        
    ]                                                                              
}   
```

**Comment by noodlylight** [comment]
Hello there, 

I think I have the exact same problem.

```
[03:24:22] INFO candybar beta-git-439.e60f2c0 (Nov  8 2014 16:40:05)
[03:24:22] INFO using config file '/home/noodlylight/.config/candybar/config.json'
[03:24:22] INFO loading theme 'file:////usr/share/candybar/theme-default/index.html'
Segmentation fault (core dumped)

```

I compiled a debug build following the instructions in CONTRIBUTING.asciidoc

```
[03:28:35] INFO candybar beta-git-439.e60f2c0 (Nov  9 2014 03:52:29)
[03:28:35] INFO using config file '/home/noodlylight/.config/candybar/config.json'
[03:28:35] INFO loading theme 'file:////usr/share/candybar/theme-default/index.html'
[03:28:35] DEBUG webkit: window object cleared
[03:28:35] DEBUG starting 7 widget threads
Segmentation fault (core dumped)
```

Running inside gdb gives:

```
Reading symbols from candybar...done.
(gdb) run
Starting program: /home/noodlylight/candydebug/candybar/out/bin/candybar 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[03:30:39] INFO candybar beta-git-439.e60f2c0 (Nov  9 2014 03:52:29)
[New Thread 0x7fffe4403700 (LWP 24585)]
[New Thread 0x7fffe3c02700 (LWP 24586)]
[New Thread 0x7fffe32ff700 (LWP 24587)]
[03:30:39] INFO using config file '/home/noodlylight/.config/candybar/config.json'
[03:30:39] INFO loading theme 'file:////usr/share/candybar/theme-default/index.html'
[New Thread 0x7fff99923700 (LWP 24588)]
[New Thread 0x7fff99122700 (LWP 24589)]
[New Thread 0x7fff98921700 (LWP 24590)]
[New Thread 0x7fff8bfff700 (LWP 24591)]
[New Thread 0x7fff8afec700 (LWP 24592)]
[New Thread 0x7fff8a1bf700 (LWP 24593)]
[03:30:39] DEBUG webkit: window object cleared
[03:30:39] DEBUG starting 7 widget threads
[New Thread 0x7fff88f57700 (LWP 24594)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff88f57700 (LWP 24594)]
0x00007fff895a3fbb in widget_update (widget=0x8cfe20, ewmh=0x7fff78005fd0, screen_nbr=0) at ../src/widgets/desktops.c:62
62              desktops[client_desktop].clients_len++;
(gdb) where
#0  0x00007fff895a3fbb in widget_update (widget=0x8cfe20, ewmh=0x7fff78005fd0, screen_nbr=0) at ../src/widgets/desktops.c:62
#1  0x00007fff895a4601 in widget_main (widget=0x8cfe20) at ../src/widgets/desktops.c:152
#2  0x00007ffff283a314 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff25783ed in clone () from /usr/lib/libc.so.6
(gdb) trace
Tracepoint 1 at 0x7fff895a3fbb: file ../src/widgets/desktops.c, line 62.
(gdb) c
Continuing.
[Thread 0x7fff8a1bf700 (LWP 24593) exited]
[Thread 0x7fff88f57700 (LWP 24594) exited]
[Thread 0x7fff8afec700 (LWP 24592) exited]
[Thread 0x7fff98921700 (LWP 24590) exited]
[Thread 0x7fff99122700 (LWP 24589) exited]
[Thread 0x7fff99923700 (LWP 24588) exited]
[Thread 0x7fffe32ff700 (LWP 24587) exited]
[Thread 0x7fffe3c02700 (LWP 24586) exited]
[Thread 0x7fffe4403700 (LWP 24585) exited]
[Thread 0x7fff8bfff700 (LWP 24591) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) 

```

Hope this helps!

Thanks.
